// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsgdodvvsekapjzwzwwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZ2RvZHZ2c2VrYXBqend6d3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODc0NjQsImV4cCI6MjA4NTM2MzQ2NH0.JqTdefUrvInn0sh7KBngoqcmg3_5Qh8UfwzEbLPUdSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});